name: Deploy to FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Mendapatkan informasi commit
      - name: Get Commit Info
        id: commit_info
        run: |
          echo "hash=${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --pretty=format:'%s')" >> $GITHUB_OUTPUT
          echo "files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 103.247.8.134
          username: autodeploy@koys.my.id
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /spmb-smpn21bogor/
          protocol: ftp
          port: 21
          timeout: 60000
          log-level: verbose
          dangerous-clean-slate: false

      - name: Notify Deploy Status
        if: always()
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://webhook.koys.my.id/webhook/deployment
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{
            "repository_id": 4, 
            "status": "${{ job.status }}", 
            "message": "Deployment completed with status ${{ job.status }}", 
            "commit_hash": "${{ steps.commit_info.outputs.hash }}", 
            "commit_message": "${{ steps.commit_info.outputs.message }}", 
            "updated_files": ${{ steps.commit_info.outputs.files }}
          }'